### ISSUE TITLE
Give the color shade to the info panel as well

### ISSUE THREAD

**Issue by msaharia** [hydrosenselab/official-website#11]
![Screenshot 2022-05-30 at 9 54 05 PM](https://user-images.githubusercontent.com/2014301/171031359-439da7ea-dabd-47dc-b4ef-34937d33db59.png)

This panel should have this color as well -
![Screenshot 2022-05-30 at 9 54 43 PM](https://user-images.githubusercontent.com/2014301/171031434-eaff2462-10ec-449f-9dd8-138cd8b9de7d.png)

Just to keep alternate color scheme consistent.

**Comment by shreyagupta30** [comment]
Hello sir. The current colour scheming fits the alternate pattern (info panel starting from white).
The tagline section and the cards below it are all part of one component so it won't be alternating.

**Comment by msaharia** [comment]
Understood! Thanks. Can we give this one the beige color?

![Screenshot 2022-06-01 at 10 20 23 AM](https://user-images.githubusercontent.com/2014301/171330091-962b645d-2d23-4423-81c3-e3bae9a98307.png)

Ignore and close this issue if not possible.

**Comment by shreyagupta30** [comment]
Added the colour, sir!
