### ISSUE TITLE
Reduce whitespace between PI bio and research areas.

### ISSUE THREAD

**Issue by msaharia** [hydrosenselab/official-website#12]
![Screenshot 2022-05-30 at 9 55 41 PM](https://user-images.githubusercontent.com/2014301/171031566-6b03b55d-7ca0-4d08-9693-a78e472d72de.png)

The whitespace between PI bio and research areas can be reduced to make it more compact.

**Comment by shreyagupta30** [comment]
Hello sir. The space is a consistent design layout (you can refer every heading below). But I have increased the size of the text so that it looks consistent.
