### ISSUE TITLE
Reducing whitespace in frontpage matter

### ISSUE THREAD

**Issue by msaharia** [hydrosenselab/official-website#5]
<img width="997" alt="Screenshot 2022-05-21 at 4 07 28 PM" src="https://user-images.githubusercontent.com/2014301/169857243-8d6deea8-9cb5-498b-99a6-c4529dd13a89.png">

Can we reduce the  vertical whitespace without messing up the responsive design.

**Comment by shreyagupta30** [comment]
Hello sir. I am not sure which page does this image belongs to. Can you please provide the URL?

**Comment by msaharia** [comment]
Sorry, wrong image uploaded. Please check now.

**Comment by shreyagupta30** [comment]
Fixed!
